### ISSUE TITLE
Would you maintain the ext?

### ISSUE THREAD

**Issue by makasim** [nikic/comparable#1]
I am gonna write the money lib (something like this https://github.com/mathiasverraes/money) but it would use your extension. The only fear I have: "would you fix bugs if they appear while using your extension, Do you have time for that?". I am doing PRs to other php open source project all the time but here is C code which I do not know well.

**Comment by makasim** [comment]
Other this: Would you consider this ext "ready for production use?"

**Comment by nikic** [comment]
I have no problem maintaining this ext. It shouldn't be a problem to use this in production, apart from the usual issues that arise when using extensions (e.g. typically being incompatible with Windows as no-one knows how to build extensions there...)

In your particular case it might make sense to use something like the operator ext (http://pecl.php.net/package/operator) as you also have a few other operators you might want to overload :)

**Comment by makasim** [comment]
> In your particular case it might make sense to use something like the operator ext (http://pecl.php.net/package/operator) as you also have a few other operators you might want to overload :)

I tried it and it not works with [static assigments](https://github.com/php/pecl-php-operator/pull/1). Would you be able to support that extension (as it covers more usecases then this one)?

**Comment by makasim** [comment]
I know very little about C++ and php internals and it makes me said as I prefer contribute myself to open source project.
